name: Update ADS Metrics
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Browser Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libnss3 libasound2 wget unzip
          pip install requests-html
          # This downloads the actual browser engine
          python -m pyppeteer-install 

      - name: Run scraper
        run: python update_metrics.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add metrics.json
          git commit -m "Update ADS metrics" || exit 0
          git push
